# Generated by Django 4.2.6 on 2023-10-28 15:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('45f599d6-c755-47d6-9514-1e8545c16bda'), editable=False, primary_key=True, serialize=False),
        ),
    ]
