# Generated by Django 4.2.6 on 2023-10-29 06:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_basemodel_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('4a75db7b-9300-485f-bda4-bb6f2c53a0ed'), editable=False, primary_key=True, serialize=False),
        ),
    ]
