# Generated by Django 4.2.6 on 2023-10-29 08:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_basemodel_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('a7448dd9-8f22-4038-b2e4-7ce6dd4ee946'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='TimingTodo',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.basemodel')),
                ('timing', models.DateField()),
                ('todoo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.todo')),
            ],
            bases=('home.basemodel',),
        ),
    ]
